# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import notification_pb2 as app_dot_protos_dot_notification__pb2


class NotificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNotification = channel.unary_unary(
                '/notification.NotificationService/SendNotification',
                request_serializer=app_dot_protos_dot_notification__pb2.NotificationRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_notification__pb2.NotificationResponse.FromString,
                )
        self.GetUserNotifications = channel.unary_unary(
                '/notification.NotificationService/GetUserNotifications',
                request_serializer=app_dot_protos_dot_notification__pb2.UserNotificationsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_notification__pb2.UserNotificationsResponse.FromString,
                )
        self.MarkNotificationAsRead = channel.unary_unary(
                '/notification.NotificationService/MarkNotificationAsRead',
                request_serializer=app_dot_protos_dot_notification__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_notification__pb2.MarkAsReadResponse.FromString,
                )


class NotificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNotification(self, request, context):
        """Send a notification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserNotifications(self, request, context):
        """Get notifications for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkNotificationAsRead(self, request, context):
        """Mark a notification as read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=app_dot_protos_dot_notification__pb2.NotificationRequest.FromString,
                    response_serializer=app_dot_protos_dot_notification__pb2.NotificationResponse.SerializeToString,
            ),
            'GetUserNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserNotifications,
                    request_deserializer=app_dot_protos_dot_notification__pb2.UserNotificationsRequest.FromString,
                    response_serializer=app_dot_protos_dot_notification__pb2.UserNotificationsResponse.SerializeToString,
            ),
            'MarkNotificationAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkNotificationAsRead,
                    request_deserializer=app_dot_protos_dot_notification__pb2.MarkAsReadRequest.FromString,
                    response_serializer=app_dot_protos_dot_notification__pb2.MarkAsReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/SendNotification',
            app_dot_protos_dot_notification__pb2.NotificationRequest.SerializeToString,
            app_dot_protos_dot_notification__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/GetUserNotifications',
            app_dot_protos_dot_notification__pb2.UserNotificationsRequest.SerializeToString,
            app_dot_protos_dot_notification__pb2.UserNotificationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkNotificationAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/MarkNotificationAsRead',
            app_dot_protos_dot_notification__pb2.MarkAsReadRequest.SerializeToString,
            app_dot_protos_dot_notification__pb2.MarkAsReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
