"""Create consent records and data sharing log tables

Revision ID: 18658977e8ba
Revises: b6e299cb0abb
Create Date: 2025-06-26 08:04:08.250292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18658977e8ba'
down_revision: Union[str, Sequence[str], None] = 'b6e299cb0abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('data_fiduciary_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'REVOKED', 'EXPIRED', name='consentstatus'), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('data_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('consent_artifact', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['data_fiduciary_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_data_fiduciary_id'), 'consent_records', ['data_fiduciary_id'], unique=False)
    op.create_index(op.f('ix_consent_records_patient_id'), 'consent_records', ['patient_id'], unique=False)
    op.create_table('data_sharing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consent_record_id', sa.UUID(), nullable=False),
    sa.Column('data_consumer_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('data_accessed', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('purpose_fulfilled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.ForeignKeyConstraint(['data_consumer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_sharing_logs')
    op.drop_index(op.f('ix_consent_records_patient_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_data_fiduciary_id'), table_name='consent_records')
    op.drop_table('consent_records')
    # ### end Alembic commands ###
