"""Implement full RBAC models

Revision ID: 3819b1e67bd0
Revises: ab2c01a74ec7
Create Date: 2025-06-26 17:59:17.180948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3819b1e67bd0'
down_revision: Union[str, Sequence[str], None] = 'ab2c01a74ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
