"""Add hierarchical metadata and category to medical_documents

Revision ID: 5f48fd25e54d
Revises: 3819b1e67bd0
Create Date: 2025-06-27 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5f48fd25e54d'
# --- THIS LINE IS CORRECTED ---
down_revision: Union[str, None] = '3819b1e67bd0' # This must match the 'Revises' ID in your previous migration file
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


documentcategory = postgresql.ENUM('LAB_REPORT', 'PRESCRIPTION', 'DISCHARGE_SUMMARY', 'INVOICE', 'INSURANCE', 'OTHER', name='documentcategory')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the ENUM type in the database first
    documentcategory.create(op.get_bind(), checkfirst=False)
    
    op.add_column('medical_documents', sa.Column('source_organization_id', sa.UUID(), nullable=True))
    op.add_column('medical_documents', sa.Column('source_practitioner_id', sa.UUID(), nullable=True))
    # Use the server_default parameter for enums in new columns on existing tables
    op.add_column('medical_documents', sa.Column('document_category', documentcategory, server_default='OTHER', nullable=False))
    op.create_index(op.f('ix_medical_documents_source_organization_id'), 'medical_documents', ['source_organization_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_source_practitioner_id'), 'medical_documents', ['source_practitioner_id'], unique=False)
    op.create_foreign_key('fk_medical_documents_source_org', 'medical_documents', 'organizations', ['source_organization_id'], ['id'])
    op.create_foreign_key('fk_medical_documents_source_prac', 'medical_documents', 'users', ['source_practitioner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_medical_documents_source_prac', 'medical_documents', type_='foreignkey')
    op.drop_constraint('fk_medical_documents_source_org', 'medical_documents', type_='foreignkey')
    op.drop_index(op.f('ix_medical_documents_source_practitioner_id'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_source_organization_id'), table_name='medical_documents')
    op.drop_column('medical_documents', 'document_category')
    op.drop_column('medical_documents', 'source_practitioner_id')
    op.drop_column('medical_documents', 'source_organization_id')
    
    # Drop the ENUM type from the database
    documentcategory.drop(op.get_bind(), checkfirst=False)
    
    # ### end Alembic commands ###