"""Enhance organization model with full details

Revision ID: 96c0e5b90ddc
Revises: 892d97870219
Create Date: 2025-06-25 11:20:04.197525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c0e5b90ddc'
down_revision: Union[str, Sequence[str], None] = '892d97870219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('abha_facility_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('license_details', sa.JSON(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column('organizations', sa.Column('contact_info', sa.JSON(), nullable=True))
    op.add_column('organizations', sa.Column('subscription_tier', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_organizations_abha_facility_id'), 'organizations', ['abha_facility_id'], unique=True)
    op.create_index(op.f('ix_organizations_registration_number'), 'organizations', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_registration_number'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_abha_facility_id'), table_name='organizations')
    op.drop_column('organizations', 'subscription_tier')
    op.drop_column('organizations', 'contact_info')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'license_details')
    op.drop_column('organizations', 'abha_facility_id')
    op.drop_column('organizations', 'registration_number')
    op.drop_column('organizations', 'type')
    # ### end Alembic commands ###
