"""Consolidate all model updates for User, Patient, and Connection

Revision ID: b6e299cb0abb
Revises: 31500afadfb2
Create Date: 2025-06-26 07:32:49.149193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e299cb0abb'
down_revision: Union[str, Sequence[str], None] = '31500afadfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_primary_phone'), table_name='patients')
    op.create_index(op.f('ix_patients_primary_phone'), 'patients', ['primary_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_primary_phone'), table_name='patients')
    op.create_index(op.f('ix_patients_primary_phone'), 'patients', ['primary_phone'], unique=True)
    # ### end Alembic commands ###
