"""update all models

Revision ID: c31503c45029
Revises: 96c0e5b90ddc
Create Date: 2025-06-25 17:24:13.425385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c31503c45029'
down_revision: Union[str, Sequence[str], None] = '96c0e5b90ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('hashed_aadhaar', sa.String(), nullable=True),
    sa.Column('aadhaar_last_4_digits', sa.String(length=4), nullable=True),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=True),
    sa.Column('aadhaar_verification_date', sa.DateTime(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('s3_data_prefix', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('s3_data_prefix')
    )
    op.create_index(op.f('ix_patients_hashed_aadhaar'), 'patients', ['hashed_aadhaar'], unique=True)
    op.create_index(op.f('ix_patients_primary_phone'), 'patients', ['primary_phone'], unique=True)
    op.create_table('patient_insurances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_insurances_policy_number'), 'patient_insurances', ['policy_number'], unique=False)
    op.add_column('users', sa.Column('abha_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('personal_info', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_abha_id'), 'users', ['abha_id'], unique=True)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_abha_id'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'profile_data')
    op.drop_column('users', 'personal_info')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'role')
    op.drop_column('users', 'abha_id')
    op.drop_index(op.f('ix_patient_insurances_policy_number'), table_name='patient_insurances')
    op.drop_table('patient_insurances')
    op.drop_index(op.f('ix_patients_primary_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_hashed_aadhaar'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
